# 프로젝트 Root 폴더
version: '3.2'

services: 
  frontend:
    image: frontend-vue
    build:
      context: frontend/
      dockerfile: Dockerfile2.dev
    ports:
      - "80:80"
      - "443:443" 
    # [인증서 파일 저장 경로]:/var/www/html
    volumes:
      - /home/ubuntu/docker-volume/ssl_key:/var/www/html
    container_name: "frontend"
  
  backend:
    image: backend-spring
    build:
      context: backend/EmotionPlanet/
      dockerfile: Dockerfile.dev
    ports:
      - "8443:8443"  
    volumes:
      - /home/ubuntu/docker-volume/ssl_key:/root
    container_name: "backend"
